// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylhjunzkdeqpruwfnjsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsaGp1bnprZGVxcHJ1d2ZuanNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODEzNzUsImV4cCI6MjA2MTQ1NzM3NX0.x2wsLXkWKcQ1P_fdCOxFsOwzS0OSR79-vXmSGuKI0r8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);